Repository JetBrains/azure-tools-for-intellij, pull requests merged in 2020-12, with the labels that each got.

#399 Fix #72. Add ability to deployt to Web of Function App Deployment Slots
  PluginsAndFeatures/azure-toolkit-for-intellij/resources/META-INF/platformPlugin.xml
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/resources/messages/RiderAzureMessages.properties
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/database/config/ui/DatabasePublishComponent.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/FunctionAppRunState.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/runstate/FunctionAppDeployStateUtil.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/ui/FunctionAppPublishComponent.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/validator/FunctionAppConfigValidator.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/model/FunctionAppPublishModel.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/webapp/config/RiderWebAppRunState.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/webapp/config/runstate/WebAppDeployStateUtil.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/webapp/config/ui/WebAppPublishComponent.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/webapp/config/ui/WebAppPublishPanel.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/webapp/config/validator/WebAppConfigValidator.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/webapp/model/WebAppPublishModel.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/ui/component/appservice/AppExistingComponent.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/ui/component/appservice/DeploymentSlotPublishSettingsPanel.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/ui/component/appservice/ExistingAppsTableComponent.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/test/kotlin/com/microsoft/intellij/runner/functionapp/config/validator/FunctionAppConfigValidatorTest.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/test/kotlin/com/microsoft/intellij/runner/webapp/config/validator/WebAppConfigValidatorTest.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/azure/toolkit/intellij/common/AzureComboBox.java
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/webapp/WebAppNode.java
  Utils/azuretools-core/src/com/microsoft/azuretools/core/mvp/model/webapp/AzureWebAppMvpModel.java
Labels: enhancement, new feature

#402 Fix #401. Add Deployment Slots for Function Apps in Azure Explorer
  PluginsAndFeatures/azure-toolkit-for-eclipse/com.microsoft.azuretools.azureexplorer/src/com/microsoft/azuretools/azureexplorer/helpers/UIHelperImpl.java
  PluginsAndFeatures/azure-toolkit-for-intellij/idea/src/com/microsoft/intellij/serviceexplorer/NodeJavaActionsMap.java
  PluginsAndFeatures/azure-toolkit-for-intellij/resources/META-INF/platformPlugin.xml
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/resources/messages/RiderAzureMessages.properties
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/FunctionAppRunState.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/serviceexplorer/RiderNodeActionsMap.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/serviceexplorer/azure/functionapp/actions/FunctionAppCreateAction.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/serviceexplorer/azure/functionapp/actions/FunctionAppCreateDeploymentSlotAction.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/ui/forms/appservice/functionapp/slot/FunctionAppCreateDeploymentSlotComponent.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/ui/forms/appservice/functionapp/slot/FunctionAppCreateDeploymentSlotDialog.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/ui/forms/appservice/slot/CreateDeploymentSlotComponent.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/ui/forms/appservice/slot/CreateDeploymentSlotDialog.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/ui/forms/appservice/webapp/slot/WebAppCreateDeploymentSlotComponent.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/ui/forms/appservice/webapp/slot/WebAppCreateDeploymentSlotDialog.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/helpers/UIHelperImpl.java
  PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/serviceexplorer/DefaultNodeActionsMap.java
  PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/serviceexplorer/azure/appservice/StartStreamingLogsAction.java
  PluginsAndFeatures/azure-toolkit-for-intellij/src/com/microsoft/intellij/serviceexplorer/azure/appservice/StopStreamingLogsAction.java
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/helpers/UIHelper.java
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/appservice/AzureAppServiceModule.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/appservice/AzureAppServiceModulePresenter.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/appservice/functionapp/AzureFunctionAppModule.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/appservice/functionapp/AzureFunctionAppModulePresenter.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/appservice/functionapp/FunctionAppNode.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/appservice/functionapp/FunctionAppNodePresenter.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/appservice/functionapp/functions/FunctionNode.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/appservice/functionapp/functions/FunctionNodePresenter.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/appservice/slot/DeploymentSlotModuleBase.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/appservice/slot/DeploymentSlotModulePresenterBase.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/appservice/slot/DeploymentSlotModuleView.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/appservice/slot/DeploymentSlotNodeBase.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/appservice/slot/DeploymentSlotNodePresenterBase.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/appservice/slot/DeploymentSlotNodeView.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/function/FunctionModule.java
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/function/FunctionNode.java
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/function/SubFunctionNode.java
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/function/deploymentslot/FunctionDeploymentSlotModule.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/function/deploymentslot/FunctionDeploymentSlotModulePresenter.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/function/deploymentslot/FunctionDeploymentSlotNode.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/function/deploymentslot/FunctionDeploymentSlotNodePresenter.kt
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/webapp/WebAppNode.java
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/webapp/base/WebAppBaseNode.java
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/webapp/deploymentslot/DeploymentSlotModule.java
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/webapp/deploymentslot/DeploymentSlotModulePresenter.java
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/webapp/deploymentslot/DeploymentSlotNode.java
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/webapp/deploymentslot/DeploymentSlotNodePresenter.java
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/webapp/deploymentslot/DeploymentSlotPropertyViewPresenter.java
  Utils/azuretools-core/src/com/microsoft/azuretools/core/mvp/model/functionapp/AzureFunctionAppMvpModel.kt
  Utils/azuretools-core/src/com/microsoft/azuretools/core/mvp/model/webapp/AzureWebAppMvpModel.java
Labels: enhancement

#407 Fix #406. Fix sorting sub nodes in Function Node in Azure Explorer
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/function/FunctionNode.java
  Utils/azure-explorer-common/src/com/microsoft/tooling/msservices/serviceexplorer/azure/webapp/WebAppNode.java
Labels: enhancement

#408 Fix RIDER-48182. Remove port argument from command line for running function app parameters
  PluginsAndFeatures/azure-toolkit-for-intellij/resources/META-INF/platformPlugin.xml
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/resources/messages/RiderAzureMessages.properties
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsHostConfigurationParameters.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsHostConfigurationViewModel.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsRunnableProjectUtil.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/localsettings/FunctionLocalSettings.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/localsettings/FunctionLocalSettingsParser.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/localsettings/FunctionLocalSettingsUtil.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/identity/ad/appsettings/AppSettingsAzureAdSectionManager.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/util/JsonParser.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/test-integration/org/cases/runconfig/functionapp/FunctionHostConfigurationEditorTest.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/test-integration/org/cases/runconfig/functionapp/FunctionHostConfigurationParametersTest.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/test/kotlin/org/jetbrains/plugins/azure/functions/run/AzureFunctionsRunnableProjectUtilTest.kt
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/testData/org/cases/runconfig/functionapp/FunctionHostConfigurationEditorTest/testFunctionHost_PortInCommandLineAndLocalSettings/source/local.settings.json
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/testData/org/cases/runconfig/functionapp/FunctionHostConfigurationEditorTest/testFunctionHost_PortInLocalSettingsJson/source/local.settings.json
Labels: bug

#410 Switch to release IDEA SDK and Eap 10 Rider SDK
  PluginsAndFeatures/azure-toolkit-for-intellij/gradle.properties
  PluginsAndFeatures/azure-toolkit-for-intellij/resources/META-INF/platformPlugin.xml
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/ReSharper.Azure/src/Azure.Daemon/RunMarkers/FunctionAppRunMarkerAttributeIds.cs
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/ReSharper.Azure/src/Azure.Daemon/RunMarkers/FunctionAppRunMarkerGutterMark.cs
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/ReSharper.Azure/src/Azure.Daemon/RunMarkers/FunctionAppRunMarkerProvider.cs
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/ReSharper.Azure/src/Azure.Daemon/RunMarkers/FunctionAppRunMarkersThemedIcons.cs
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/icons/RiderIconsPatcherRegistrar.kt
Labels: release

#412 Move custom Settings menu into Idea Plugin module sources
  PluginsAndFeatures/azure-toolkit-for-intellij/idea/resources/META-INF/plugin.xml
  PluginsAndFeatures/azure-toolkit-for-intellij/resources/META-INF/platformPlugin.xml
Labels: task

#416 Fix #415. Fix Azurite settings panel workspace path
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/configuration/AzureRiderSettings.kt
Labels: bug

#418 Update change-notes with a bug fix for #415.
  PluginsAndFeatures/azure-toolkit-for-intellij/resources/META-INF/platformPlugin.xml
Labels: release

#419 Update AzureFunctionsProjectDetector for .NET 5 functions projects #413
  PluginsAndFeatures/azure-toolkit-for-intellij/rider/ReSharper.Azure/src/Azure.Project/FunctionApp/FunctionAppProjectDetector.cs
Labels: task
